name: eticon_api
description: 'This package will help you quickly and easily work with HTTP REQUESTS. All you need to do is select one of the 4 required requests: GET, POST, DELETE, PUT'
version: 1.3.12
homepage: https://github.com/kensamare/eticon_api

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
