name: eticon_api
description: 'This package will help you quickly and easily work with HTTP REQUESTS. All you need to do is select one of the 4 required requests: GET, POST, DELETE, PUT, PATCH'
version: 2.0.5
homepage: https://github.com/kensamare/eticon_api

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
